install:
  - npm install
script:
  - gulp
deploy:
  provider: npm
  email: codonnell822+npm@outlook.com
  api_key:
    secure: lM9RWO7EOkq55IJ7/I1EoULMnKcO1yuHpap+4K/Wbxu3azt5fpocarO8BV+OMntgD4ZuT9rdwwiWP955Wt2KA6pQf9akY+5nQ/T1UgIBs7/USXPetPXBEzlG7NHSp2MszM1LWPpXu40UtoV0ESXFeWbf83STwL/N9haYGQLtaeDyYoQJlG1Ri7zwYAWnvShG4BQ8gdwpTBpPaeM8YNNUB461M9D++z3D2K5ZOJd/K87bU0+1EzdHRYPl2xXz73t3UDGZK8tPS4oJcJ6vsODmCz1HT39YBjOqLpLprsaYhLGm34nJeQJYKWwub0hgTSQHzIIVxw7hbWSg7XVWpchWw5SPNay1248Ad29wg4rVSLOuWcOTCIb5c9Ei37y+x31xON90YMtw9DT+TQppy9+HOezn2T4XpxjwHR0bEzlhfYAxI0RDfhbVlQuwtmtoceIubmdHNHHdHti6e5N0XrbC2mOUT3UT1mey+dSWzk+JKBWH4yBtM5ybUqWk94VV967JF/6qyj5XZAhoNYpviCb451+En4IAqewANMfwUupfXr7plUaOf9BLCkPoxIGNkDBpoNQNZbgJkUHIvbjyUuWgimctl3DcpkancAqep00zZ8I/09j7ocEG9h0BuCL55fTG90fXF/RuRrwZUEmYfOElWwirfuEEyvdxx9KXgs0HuL0=
  on:
    tags: true
    branch: master
    repo: codfish/jquery-data-remote
